# Generated by Django 5.0.4 on 2024-05-23 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.permission')),
            ],
            options={
                'permissions': (('add_staffuser', 'Can add Staff users'), ('change_staffuser', 'Can edit Staff users'), ('view_staffuser', 'Can view Staff users'), ('delete_staffuser', 'Can delete Staff users')),
            },
        ),
    ]
