# Generated by Django 5.0.4 on 2024-11-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tax_percentage', models.CharField(choices=[('5', '5'), ('10', '10'), ('15', '15')], max_length=20, null=True)),
                ('tax_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('adjusted_amount', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
