# Generated by Django 5.0.4 on 2024-05-17 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='locationName',
        ),
    ]
