# Generated by Django 5.0.4 on 2024-11-13 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_hospitalservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.invoicedata')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.hospitalservice')),
            ],
        ),
        migrations.AddField(
            model_name='invoicedata',
            name='service',
            field=models.ManyToManyField(through='doctor.InvoiceItem', to='doctor.hospitalservice'),
        ),
    ]
