# Generated by Django 5.0.4 on 2024-10-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_cartitem_customer_alter_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='products',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='category',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
