# Generated by Django 5.0.4 on 2024-11-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_invoiceitem_invoicedata_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalservice',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
