# Generated by Django 5.0.4 on 2024-11-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_hospitalservice_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalservice',
            name='adjusted_amount',
        ),
        migrations.RemoveField(
            model_name='hospitalservice',
            name='tax_amount',
        ),
    ]
