# Generated by Django 5.0.4 on 2024-10-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='patient_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
