# Generated by Django 5.0.4 on 2024-11-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_hospitalservice_adjusted_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hospitalservice',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
