# Generated by Django 5.0.4 on 2024-05-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_patientdetails_guardiandetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordetails',
            old_name='name',
            new_name='doctor_name',
        ),
    ]
