# Generated by Django 5.0.4 on 2024-05-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_rename_name_doctordetails_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='email',
            field=models.EmailField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='guardiandetails',
            name='email',
            field=models.EmailField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='email',
            field=models.EmailField(default='', max_length=50, unique=True),
        ),
    ]
