# Generated by Django 5.0.4 on 2024-11-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_hospitalservice_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalservice',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hospitalservice',
            name='tax_percentage',
            field=models.FloatField(default=0),
        ),
    ]
