# Generated by Django 5.0.4 on 2024-10-31 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_patientdetails_patient_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='patient_number',
        ),
    ]
