# Generated by Django 5.0.4 on 2024-05-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_doctordetails_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('email', models.EmailField(default='', max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
