# Generated by Django 5.0.4 on 2024-11-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_hospitalservice_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedata',
            name='adjusted_amount',
        ),
        migrations.RemoveField(
            model_name='invoicedata',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoicedata',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='invoicedata',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='invoicedata',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='invoicedata',
            name='total_amount',
        ),
    ]
