# Generated by Django 5.0.4 on 2024-10-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_remove_patientdetails_patient_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='patient_number',
            field=models.IntegerField(null=True),
        ),
    ]
