# Generated by Django 5.0.4 on 2024-10-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_patientdetails_patient_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbed',
            name='bedCategory_name',
        ),
        migrations.RemoveField(
            model_name='addbed',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='admissiondetails',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='admissiondetails',
            name='patient_status',
        ),
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='guardiandetails',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='incomedetails',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='invoicerelation',
            name='invoice_relate',
        ),
        migrations.RemoveField(
            model_name='maininvoice',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='subinvoice',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='nursedetails',
            name='department_name',
        ),
        migrations.DeleteModel(
            name='PharmacistDetails',
        ),
        migrations.DeleteModel(
            name='TreatmentDetails',
        ),
        migrations.DeleteModel(
            name='BedCategory',
        ),
        migrations.DeleteModel(
            name='AddBed',
        ),
        migrations.DeleteModel(
            name='AdmissionDetails',
        ),
        migrations.DeleteModel(
            name='PatientStatus',
        ),
        migrations.DeleteModel(
            name='AppointmentDetails',
        ),
        migrations.DeleteModel(
            name='GuardianDetails',
        ),
        migrations.DeleteModel(
            name='IncomeDetails',
        ),
        migrations.DeleteModel(
            name='InvoiceDetail',
        ),
        migrations.DeleteModel(
            name='InvoiceRelation',
        ),
        migrations.DeleteModel(
            name='PatientDetails',
        ),
        migrations.DeleteModel(
            name='MainInvoice',
        ),
        migrations.DeleteModel(
            name='SubInvoice',
        ),
        migrations.DeleteModel(
            name='NurseDetails',
        ),
    ]
