# Generated by Django 5.0.4 on 2024-11-14 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_remove_invoicedata_adjusted_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicerelation',
            name='invoice_relate',
        ),
        migrations.RemoveField(
            model_name='maininvoice',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='subinvoice',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceDetail',
        ),
        migrations.DeleteModel(
            name='InvoiceRelation',
        ),
        migrations.DeleteModel(
            name='MainInvoice',
        ),
        migrations.DeleteModel(
            name='SubInvoice',
        ),
    ]
