# Generated by Django 5.0.4 on 2024-11-15 05:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_remove_invoicerelation_invoice_relate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('capacity', models.SmallIntegerField(default=0)),
                ('numberOfBeds', models.SmallIntegerField(default=0)),
                ('roomType', models.CharField(choices=[('King', 'King'), ('Luxury', 'Luxury'), ('Normal', 'Normal'), ('Economic', 'Economic'), ('General Ward', 'General Ward')], max_length=20)),
                ('price', models.FloatField()),
                ('statusStartDate', models.DateField(null=True)),
                ('statusEndDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfReservation', models.DateField(default=django.utils.timezone.now)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patientdetails')),
                ('roomNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.room')),
            ],
        ),
        migrations.CreateModel(
            name='Dependees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patientdetails')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.booking')),
            ],
        ),
    ]
