# Generated by Django 5.0.4 on 2024-05-31 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_bedcategory_pharmacistdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedcategory',
            name='slug',
        ),
    ]
