# Generated by Django 5.0.4 on 2024-10-31 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_remove_addbed_bedcategory_name_remove_addbed_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedCategory_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('adjusted_amount', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_number', models.GeneratedField(db_persist=True, expression=models.F('id'), output_field=models.IntegerField())),
                ('patient_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('blood_group', models.CharField(blank=True, choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('pin_code', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(default='', max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('patient_image', models.BinaryField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacistDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacist_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('pin_code', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(default='', max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('charges', models.CharField(blank=True, max_length=50, null=True)),
                ('charges_tax', models.CharField(blank=True, choices=[('10%', '10%'), ('15%', '15%'), ('20%', '20%')], max_length=20, null=True)),
                ('pharmacist_image', models.BinaryField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=50)),
                ('treatment_price', models.CharField(max_length=50)),
                ('tax', models.CharField(choices=[('5%', '5%'), ('10%', '10%'), ('15%', '15%')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_title', models.CharField(blank=True, max_length=50, null=True)),
                ('subtotal_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_relate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='doctor.invoicedetail')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='NurseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('pin_code', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(default='', max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('salary', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_tax', models.CharField(blank=True, choices=[('10%', '10%'), ('15%', '15%'), ('20%', '20%')], max_length=20, null=True)),
                ('nurse_image', models.BinaryField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctordepartment')),
            ],
        ),
        migrations.CreateModel(
            name='MainInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('adjusted_amount', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patientdetails')),
            ],
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patientdetails'),
        ),
        migrations.CreateModel(
            name='IncomeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(blank=True, choices=[('PD', 'Paid'), ('PNDG', 'PENDING'), ('NPD', 'Not Paid')], max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('CSH', 'Cash'), ('CRD', 'Card'), ('UPI', 'Upi')], max_length=20, null=True)),
                ('payment_details', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('payment_amount', models.CharField(max_length=50)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='GuardianDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('email', models.EmailField(default='', max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(blank=True, null=True)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctordepartment')),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorinfo')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='AddBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=50)),
                ('charges', models.CharField(max_length=50)),
                ('tax', models.CharField(choices=[('10%', '10%'), ('15%', '15%'), ('20%', '20%')], max_length=20)),
                ('bedCategory_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.bedcategory')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(blank=True, null=True)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorinfo')),
                ('patient_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patientstatus')),
            ],
        ),
        migrations.CreateModel(
            name='SubInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_title', models.CharField(blank=True, max_length=50, null=True)),
                ('subtotal_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.maininvoice')),
            ],
        ),
    ]
