# Generated by Django 5.0.4 on 2024-11-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_bedcategory_invoicedetail_patientdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='patient_number',
        ),
    ]
