# Generated by Django 5.0.4 on 2024-05-31 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_remove_bedcategory_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bedcategory',
            old_name='bedCatagary_name',
            new_name='bedCategary_name',
        ),
    ]
