# Generated by Django 5.0.4 on 2024-11-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_room_booking_dependees_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
