# Generated by Django 5.0.4 on 2024-05-31 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_rename_bedcatagary_name_bedcategory_bedcategary_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=50)),
                ('charges', models.CharField(max_length=50)),
                ('tax', models.CharField(choices=[('10%', '10%'), ('15%', '15%'), ('20%', '20%')], max_length=20)),
                ('bed_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.bedcategory')),
            ],
        ),
    ]
