# Generated by Django 5.0.4 on 2024-05-31 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_addbed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addbed',
            old_name='bed_category',
            new_name='bedCategary_name',
        ),
    ]
