# Generated by Django 5.0.4 on 2024-11-01 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_delete_patientnumber_patientdetails_patient_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='patient_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patientnumber'),
        ),
    ]
