# Generated by Django 5.0.4 on 2024-11-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_patientnumber_alter_patientdetails_patient_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='patient_number',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='PatientNumber',
        ),
    ]
