# Generated by Django 5.0.4 on 2024-11-19 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomedetails',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.invoicedata'),
        ),
        migrations.AlterField(
            model_name='incomedetails',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PD', 'Paid'), ('PART', 'Partial Payment'), ('NPD', 'Not Paid')], max_length=20, null=True),
        ),
    ]
