# Generated by Django 5.0.4 on 2024-05-31 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_rename_bed_category_addbed_bedcategary_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addbed',
            old_name='bedCategary_name',
            new_name='bedCategory_name',
        ),
        migrations.RenameField(
            model_name='bedcategory',
            old_name='bedCategary_name',
            new_name='bedCategory_name',
        ),
    ]
