# Generated by Django 5.0.4 on 2024-06-02 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_rename_bedcategary_name_addbed_bedcategory_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(blank=True, null=True)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctordetails')),
                ('patient_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patientstatus')),
            ],
        ),
    ]
