# Generated by Django 5.0.4 on 2024-11-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_incomedetails_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomedetails',
            name='invoice',
        ),
    ]
