# Generated by Django 5.0.4 on 2024-06-03 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_patientstatus_admissiondetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_title', models.CharField(max_length=50)),
                ('subtotal_amount', models.CharField(max_length=50)),
                ('adjusted_amount', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patientdetails')),
            ],
        ),
    ]
