# Generated by Django 5.0.4 on 2024-11-19 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_remove_incomedetails_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomedetails',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.invoicedata'),
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.incomedetails')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.invoicedata')),
            ],
        ),
    ]
