# Generated by Django 5.0.4 on 2024-06-04 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_invoicedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(blank=True, null=True)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctordepartment')),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctordetails')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patientdetails')),
            ],
        ),
    ]
