# Generated by Django 5.0.4 on 2024-11-03 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_alter_customer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalservice',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('adjusted_amount', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patientdetails')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.hospitalservice')),
            ],
        ),
    ]
