# Generated by Django 5.0.4 on 2024-11-19 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_alter_incomedetails_patient_name_paymentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomedetails',
            name='patient_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.invoicedata'),
        ),
    ]
