# Generated by Django 5.0.4 on 2024-11-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_alter_incomedetails_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomedetails',
            name='patient_name',
        ),
    ]
