# Generated by Django 5.0.4 on 2024-06-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_appointmentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=50)),
                ('treatment_price', models.CharField(max_length=50)),
                ('tax', models.CharField(choices=[('5%', '5%'), ('10%', '10%'), ('15%', '15%')], max_length=20)),
            ],
        ),
    ]
