# Generated by Django 5.0.4 on 2024-11-03 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_hospitalservice_price_invoicedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.invoicedata')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.hospitalservice')),
            ],
        ),
    ]
