# Generated by Django 5.0.4 on 2024-11-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='reoder_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
