# Generated by Django 5.0.4 on 2024-06-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_treatmentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='doctor_image',
            field=models.ImageField(blank=True, upload_to='doctor/'),
        ),
    ]
