# Generated by Django 5.0.4 on 2024-11-19 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_remove_incomedetails_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomedetails',
            name='patient_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.invoicedata'),
        ),
    ]
