# Generated by Django 5.0.4 on 2024-06-07 09:56

import django.db.models.deletion
import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_doctordetails_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='doctor/cv/'),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='doctor_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor/'),
        ),
        migrations.CreateModel(
            name='DoctorCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=doctor.models.certificate_path)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctordetails')),
            ],
        ),
    ]
