# Generated by Django 5.0.4 on 2024-11-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_incomedetails_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomedetails',
            name='payment_amount',
            field=models.IntegerField(default=0),
        ),
    ]
