# Generated by Django 5.0.4 on 2024-11-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_stock_reoder_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='reoder_stock',
            new_name='reorder_stock',
        ),
    ]
