# Generated by Django 5.0.4 on 2024-11-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_rename_reoder_stock_stock_reorder_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
