# Generated by Django 5.0.4 on 2024-11-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_alter_incomedetails_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomedetails',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'Upi')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incomedetails',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial Payment'), ('NOTPAID', 'Not Paid')], max_length=20, null=True),
        ),
    ]
