# Generated by Django 5.0.4 on 2024-06-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_doctordetails_cv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
