# Generated by Django 5.0.4 on 2024-06-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_doctordetails_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordetails',
            name='doctor_image',
        ),
    ]
