# Generated by Django 5.0.4 on 2024-11-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_stock_stock_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_level',
        ),
    ]
