# Generated by Django 5.0.4 on 2024-06-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0022_remove_doctordetails_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='address_line',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='consulting_charge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='consulting_charge_tax',
            field=models.CharField(blank=True, choices=[('10%', '10%'), ('15%', '15%'), ('20%', '20%')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='specialization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='visiting_charge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='visiting_charge_tax',
            field=models.CharField(blank=True, choices=[('10%', '10%'), ('15%', '15%'), ('20%', '20%')], max_length=20, null=True),
        ),
    ]
