# Generated by Django 5.0.4 on 2024-11-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0022_remove_stock_stock_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_reorder_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
