# Generated by Django 5.0.4 on 2024-06-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_doctordetails_address_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='pin_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('1', 'O-'), ('2', 'O+'), ('3', 'A-'), ('4', 'A+'), ('5', 'B-'), ('6', 'B+'), ('7', 'AB-'), ('8', 'AB+')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='patient_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='pin_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
