# Generated by Django 5.0.4 on 2024-11-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_stock_stock_reorder_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedata',
            name='invoice_number',
            field=models.IntegerField(null=True),
        ),
    ]
