# Generated by Django 5.0.4 on 2024-06-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0024_doctordetails_country_doctordetails_pin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=20, null=True),
        ),
    ]
