# Generated by Django 5.0.4 on 2024-11-07 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0024_invoicedata_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedata',
            name='service',
        ),
    ]
