# Generated by Django 5.0.4 on 2024-06-18 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0025_alter_patientdetails_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursedetails',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='nursedetails',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nursedetails',
            name='department_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctordepartment'),
        ),
        migrations.AddField(
            model_name='nursedetails',
            name='nurse_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursedetails',
            name='pin_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursedetails',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nursedetails',
            name='salary_tax',
            field=models.CharField(blank=True, choices=[('10%', '10%'), ('15%', '15%'), ('20%', '20%')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nursedetails',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pharmacistdetails',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pharmacistdetails',
            name='charges',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pharmacistdetails',
            name='charges_tax',
            field=models.CharField(blank=True, choices=[('10%', '10%'), ('15%', '15%'), ('20%', '20%')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pharmacistdetails',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pharmacistdetails',
            name='pharmacist_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacistdetails',
            name='pin_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacistdetails',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
