# Generated by Django 5.0.4 on 2024-11-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0025_remove_invoicedata_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedata',
            name='service',
            field=models.ManyToManyField(through='doctor.InvoiceItem', to='doctor.hospitalservice'),
        ),
    ]
