# Generated by Django 5.0.4 on 2024-06-21 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0026_nursedetails_address_nursedetails_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(blank=True, choices=[('PD', 'Paid'), ('PNDG', 'PENDING'), ('NPD', 'Not Paid')], max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('CSH', 'Cash'), ('CRD', 'Card'), ('UPI', 'Upi')], max_length=20, null=True)),
                ('payment_details', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('payment_amount', models.CharField(max_length=50)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patientdetails')),
            ],
        ),
    ]
