# Generated by Django 5.0.4 on 2024-11-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0026_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='consulting_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='consulting_charge_tax',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '10%'), (15, '15%'), (20, '20%')], null=True),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='visiting_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='visiting_charge_tax',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '10%'), (15, '15%'), (20, '20%')], null=True),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
