# Generated by Django 5.0.4 on 2024-11-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0026_invoicedata_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedata',
            name='adjusted_amount',
        ),
        migrations.RemoveField(
            model_name='invoicedata',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoicedata',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='invoicedata',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='invoicedata',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='invoicedata',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
