# Generated by Django 5.0.4 on 2024-06-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0027_incomedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorcertificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='doctor/certificates/{instance.doctor.id}/{filename}'),
        ),
    ]
