# Generated by Django 5.0.4 on 2024-11-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0027_remove_appointment_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
