# Generated by Django 5.0.4 on 2024-11-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0027_remove_invoicedata_adjusted_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedata',
            name='adjusted_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicedata',
            name='discount_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicedata',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicedata',
            name='tax_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicedata',
            name='tax_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicedata',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
