# Generated by Django 5.0.4 on 2024-06-25 12:58

import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0028_alter_doctorcertificate_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='doctor/'),
        ),
        migrations.AlterField(
            model_name='doctorcertificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to=doctor.models.certificate_path),
        ),
    ]
