# Generated by Django 5.0.4 on 2024-11-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0028_invoicedata_adjusted_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='InvoiceData',
        ),
    ]
