# Generated by Django 5.0.4 on 2024-11-25 12:46

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0028_doctorinfo_slug_patientdetails_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='patient_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=10, prefix=''),
        ),
    ]
