# Generated by Django 5.0.4 on 2024-06-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0029_doctordetails_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='doctor/certificates'),
        ),
    ]
