# Generated by Django 5.0.4 on 2024-11-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0029_alter_patientdetails_patient_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='patient_number',
            field=models.IntegerField(null=True),
        ),
    ]
