# Generated by Django 5.0.4 on 2024-11-07 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0029_remove_invoiceitem_invoice_invoiceitem_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('total_amount', models.IntegerField(default=0)),
                ('discount_amount', models.IntegerField(default=0)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('tax_percentage', models.IntegerField(default=0)),
                ('tax_amount', models.IntegerField(default=0)),
                ('adjusted_amount', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patientdetails')),
                ('service', models.ManyToManyField(through='doctor.InvoiceItem', to='doctor.hospitalservice')),
            ],
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.invoicedata'),
        ),
    ]
