# Generated by Django 5.0.4 on 2024-11-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0030_alter_patientdetails_patient_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='patient_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
