# Generated by Django 5.0.4 on 2024-06-26 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0030_alter_doctordetails_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('specialization', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('address_line', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('pin_code', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(default='', max_length=50, unique=True)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('visiting_charge', models.CharField(blank=True, max_length=50, null=True)),
                ('visiting_charge_tax', models.CharField(blank=True, choices=[('10%', '10%'), ('15%', '15%'), ('20%', '20%')], max_length=20, null=True)),
                ('consulting_charge', models.CharField(blank=True, max_length=50, null=True)),
                ('consulting_charge_tax', models.CharField(blank=True, choices=[('10%', '10%'), ('15%', '15%'), ('20%', '20%')], max_length=20, null=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='doctor/cv/')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='doctor/certificates')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctordepartment')),
            ],
        ),
        migrations.AlterField(
            model_name='admissiondetails',
            name='doctor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorinfo'),
        ),
    ]
