# Generated by Django 5.0.4 on 2024-06-26 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0031_doctorinfo_alter_admissiondetails_doctor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinfo',
            name='certificate',
        ),
        migrations.CreateModel(
            name='CertificateDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='doctor/certificates')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorinfo')),
            ],
        ),
    ]
