# Generated by Django 5.0.4 on 2024-11-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0032_alter_patientdetails_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='email',
            field=models.EmailField(default='', max_length=50, null=True),
        ),
    ]
