# Generated by Django 5.0.4 on 2024-06-26 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0032_remove_doctorinfo_certificate_certificatedoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetails',
            name='doctor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorinfo'),
        ),
    ]
