# Generated by Django 5.0.4 on 2024-07-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0033_alter_appointmentdetails_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='discount_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='discount_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='certificatedoctor',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='doctor/certificates/'),
        ),
    ]
