# Generated by Django 5.0.4 on 2024-11-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0033_alter_patientdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='phone_number',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
