# Generated by Django 5.0.4 on 2024-07-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0034_invoicedetails_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='tax_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='tax_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
