# Generated by Django 5.0.4 on 2024-08-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0035_invoicedetails_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='invoice_title1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='invoice_title2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='subtotal_amount1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='subtotal_amount2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='invoice_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='subtotal_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
