# Generated by Django 5.0.4 on 2024-08-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0036_invoicedetails_invoice_title1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='total_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
