# Generated by Django 5.0.4 on 2024-08-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0037_invoicedetails_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_title', models.CharField(blank=True, max_length=50, null=True)),
                ('subtotal_amount', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoicedetails',
            name='invoice_title',
        ),
        migrations.RemoveField(
            model_name='invoicedetails',
            name='invoice_title1',
        ),
        migrations.RemoveField(
            model_name='invoicedetails',
            name='invoice_title2',
        ),
        migrations.RemoveField(
            model_name='invoicedetails',
            name='subtotal_amount',
        ),
        migrations.RemoveField(
            model_name='invoicedetails',
            name='subtotal_amount1',
        ),
        migrations.RemoveField(
            model_name='invoicedetails',
            name='subtotal_amount2',
        ),
    ]
