# Generated by Django 5.0.4 on 2024-08-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0038_invoice_remove_invoicedetails_invoice_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice',
            new_name='InvoiceRelation',
        ),
    ]
