# Generated by Django 5.0.4 on 2024-08-27 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0039_rename_invoice_invoicerelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='invoice_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.invoicerelation'),
        ),
    ]
