# Generated by Django 5.0.4 on 2024-08-27 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0040_invoicedetails_invoice_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('adjusted_amount', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceInfo',
            fields=[
                ('invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('adjusted_amount', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patientdetails')),
            ],
        ),
        migrations.DeleteModel(
            name='InvoiceDetails',
        ),
    ]
