# Generated by Django 5.0.4 on 2024-08-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0041_invoicedetail_invoiceinfo_delete_invoicedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceinfo',
            name='patient_name',
        ),
        migrations.DeleteModel(
            name='InvoiceRelation',
        ),
        migrations.DeleteModel(
            name='InvoiceInfo',
        ),
    ]
