# Generated by Django 5.0.4 on 2024-08-27 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0042_remove_invoiceinfo_patient_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_title', models.CharField(blank=True, max_length=50, null=True)),
                ('subtotal_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_relate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctor.invoicedetail')),
            ],
        ),
    ]
