# Generated by Django 5.0.4 on 2024-08-30 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0043_invoicerelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicerelation',
            name='invoice_relate',
        ),
    ]
