# Generated by Django 5.0.4 on 2024-08-30 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0044_remove_invoicerelation_invoice_relate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='invoice_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doctor.invoicerelation'),
        ),
    ]
