# Generated by Django 5.0.4 on 2024-09-04 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0045_invoicedetail_invoice_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='invoice_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.invoicerelation'),
        ),
    ]
