# Generated by Django 5.0.4 on 2024-09-04 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0046_alter_invoicedetail_invoice_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='invoice_relation',
        ),
        migrations.AddField(
            model_name='invoicerelation',
            name='invoice_relate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.invoicedetail'),
        ),
    ]
