# Generated by Django 5.0.4 on 2024-09-11 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0047_remove_invoicedetail_invoice_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerelation',
            name='invoice_relate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='doctor.invoicedetail'),
        ),
        migrations.AlterModelTable(
            name='invoicerelation',
            table='invoice',
        ),
    ]
