# Generated by Django 5.0.4 on 2024-09-13 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0048_alter_invoicerelation_invoice_relate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('adjusted_amount', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='SubInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_title', models.CharField(blank=True, max_length=50, null=True)),
                ('subtotal_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.maininvoice')),
            ],
        ),
    ]
