# Generated by Django 5.0.4 on 2024-09-26 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0053_stock_discount_rate_stock_price_stock_selling_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='price',
            new_name='per_unit_price',
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='price',
            new_name='per_unit_price',
        ),
        migrations.AddField(
            model_name='stock',
            name='total_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='total_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
