# Generated by Django 5.0.4 on 2024-10-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0054_rename_price_stock_per_unit_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='per_unit_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='export_to_CSV',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='issue_by',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='issue_quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='issue_to',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='receive_by',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='receive_quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='total_price',
        ),
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
