# Generated by Django 5.0.4 on 2024-10-14 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0059_remove_cartitem_cart_cartitem_customer_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.stock'),
        ),
    ]
