# Generated by Django 5.0.4 on 2024-10-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0060_customer_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='product',
        ),
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(to='doctor.stock'),
        ),
    ]
