# Generated by Django 5.0.4 on 2024-10-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0061_remove_customer_product_customer_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
