# Generated by Django 5.0.4 on 2024-10-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0063_cart_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
