# Generated by Django 5.0.4 on 2024-10-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0066_remove_cartitem_cart_customer_quantity_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='quantity',
        ),
    ]
