# Generated by Django 5.0.4 on 2024-10-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0067_remove_customer_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbed',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='addbed',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bedcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
