# Generated by Django 5.0.4 on 2024-10-25 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0068_addbed_is_active_addbed_quantity_bedcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbed',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='addbed',
            name='quantity',
        ),
        migrations.AddField(
            model_name='addbed',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patientdetails'),
        ),
        migrations.AddField(
            model_name='bedcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bedcategory',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
